language: python
matrix:
  include:
    - name: "Python 3.6 on Linux"
      python: 3.6
      dist: xenial
    - name: "PyPy 3.6 on Linux"
      python: "pypy3.6-7.1.1"
      dist: xenial
    - name: "Python 3.7 on Linux"
      python: 3.7
      dist: xenial
    - name: "Python 3.8 on Linux"
      python: 3.8
      dist: xenial
    - name: "Python 3.7 on Linux"
      os: osx
      osx_image: xcode10.2
      language: shell

cache:
  - pip

install:
  - pip3 install -r requirements-test.txt

script:
  - pytest -v -rs tests --runslow --cov

after_success:
  - codecov

notifications:
  email:
    on_success: change
    on_failure: always